### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by rsplaul** [unixb0y/AltStore-Apps#1]
I would like to compile & sideload OBSCam myself without having to install AltStore. Would you mind publishing the source code?

**Comment by unixb0y** [comment]
Hey @rsplaul of course, I planned to do so anyway! Expect it to be done tomorrow, just check my GitHub profile 😊

**Comment by unixb0y** [comment]
Sorry for the delay, very busy atm! Source now available!
https://github.com/unixb0y/OBSCam
